services:
  postgres:
    image: postgres:alpine
    container_name: postgres_nivara
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: nivara_hotels
    ports:
      - "5432:5432"
