import type { RoomType } from "./roomType.types";

export const dummyRoomTypes: RoomType[] = [
  {
    id: "rt1",
    name: "Standard Room",
    description: "Comfortable room with essential amenities.",
    capacity: 2,
    basePrice: 1800,
    isActive: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-09-20"),
  },
  {
    id: "rt2",
    name: "Deluxe Room",
    description: "Spacious room with premium furnishings.",
    capacity: 2,
    basePrice: 2800,
    isActive: true,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-09-22"),
  },
  {
    id: "rt3",
    name: "Executive Room",
    description: "Designed for business travelers.",
    capacity: 3,
    basePrice: 3500,
    isActive: true,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-09-21"),
  },
  {
    id: "rt4",
    name: "Family Room",
    description: "Ideal for families with children.",
    capacity: 4,
    basePrice: 4500,
    isActive: true,
    createdAt: new Date("2026-03-05"),
    updatedAt: new Date("2026-09-23"),
  },
  {
    id: "rt5",
    name: "Premium Suite",
    description: "Luxury suite with separate living area.",
    capacity: 4,
    basePrice: 7500,
    isActive: true,
    createdAt: new Date("2026-04-12"),
    updatedAt: new Date("2026-09-22"),
  },
  {
    id: "rt6",
    name: "Presidential Suite",
    description: "Highest-tier accommodation with premium services.",
    capacity: 6,
    basePrice: 15000,
    isActive: false,
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-09-18"),
  },
];
