import type { SelectOption } from "@/components/shared/SelectField";

export const amenitiesList: SelectOption[] = [
  { id: "wifi", name: "Wifi" },
  { id: "tv", name: "TV" },
  { id: "airvent", name: "Air Vent" },
  { id: "snowflake", name: "Air Conditioning" },
  { id: "heater", name: "Heater" },
  { id: "fan", name: "Fan" },
  { id: "bath", name: "Bath" },
  { id: "bed", name: "Bed" },
  { id: "beddouble", name: "Double Bed" },
  { id: "bedsingle", name: "Single Bed" },
  { id: "coffee", name: "Coffee" },
  { id: "utensils", name: "Utensils" },
  { id: "chefhat", name: "Kitchen" },
  { id: "refrigerator", name: "Refrigerator" },
  { id: "microwave", name: "Microwave" },
  { id: "washingmachine", name: "Washing Machine" },
  { id: "droplet", name: "Hot Water" },
  { id: "waves", name: "Swimming Pool" },
  { id: "dumbbell", name: "Gym" },
  { id: "trees", name: "Garden" },
  { id: "treepalm", name: "Resort" },
  { id: "car", name: "Parking" },
  { id: "circleparking", name: "Free Parking" },
  { id: "bike", name: "Bike Parking" },
  { id: "bus", name: "Airport Shuttle" },
  { id: "plane", name: "Airport" },
  { id: "luggage", name: "Luggage Storage" },
  { id: "lock", name: "Secure Lock" },
  { id: "keyround", name: "Room Key" },
  { id: "shieldcheck", name: "Security" },
  { id: "cctv", name: "CCTV" },
  { id: "cigaretteoff", name: "Non Smoking" },
  { id: "smile", name: "Family Friendly" },
  { id: "phone", name: "Telephone" },
  { id: "speaker", name: "Bluetooth Speaker" },
  { id: "music", name: "Music" },
  { id: "lampdesk", name: "Workspace" },
  { id: "plug", name: "Power Outlet" },
  { id: "usb", name: "USB Charging" },
  { id: "wind", name: "Ventilation" },
  { id: "sun", name: "Balcony" },
  { id: "moon", name: "Night Stay" },
  { id: "flame", name: "Fireplace" },
];

import {
  AirVent,
  Bath,
  Bed,
  BedDouble,
  BedSingle,
  Bike,
  Bus,
  Car,
  Cctv,
  ChefHat,
  CigaretteOff,
  CircleParking,
  Coffee,
  DoorOpen,
  Droplet,
  Dumbbell,
  Fan,
  Flame,
  Heater,
  KeyRound,
  LampDesk,
  Lock,
  type LucideIcon,
  Luggage,
  Microwave,
  Moon,
  Music,
  Phone,
  Plane,
  Plug,
  Refrigerator,
  ShieldCheck,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  Sun,
  TreePalm,
  Trees,
  Tv,
  Usb,
  Users,
  Utensils,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
} from "lucide-react";

export const iconsList: { [key: string]: LucideIcon } = {
  users: Users,
  sparkles: Sparkles,
  wifi: Wifi,
  tv: Tv,
  airvent: AirVent,
  snowflake: Snowflake,
  heater: Heater,
  fan: Fan,
  bath: Bath,
  bed: Bed,
  dooropen: DoorOpen,
  beddouble: BedDouble,
  bedsingle: BedSingle,
  coffee: Coffee,
  utensils: Utensils,
  chefhat: ChefHat,
  refrigerator: Refrigerator,
  microwave: Microwave,
  washingmachine: WashingMachine,
  droplet: Droplet,
  waves: Waves,
  dumbbell: Dumbbell,
  trees: Trees,
  treepalm: TreePalm,
  car: Car,
  circleparking: CircleParking,
  bike: Bike,
  bus: Bus,
  plane: Plane,
  luggage: Luggage,
  lock: Lock,
  keyround: KeyRound,
  shieldcheck: ShieldCheck,
  cctv: Cctv,
  cigaretteoff: CigaretteOff,
  smile: Smile,
  phone: Phone,
  speaker: Speaker,
  music: Music,
  lampdesk: LampDesk,
  plug: Plug,
  usb: Usb,
  wind: Wind,
  sun: Sun,
  moon: Moon,
  flame: Flame,
} as const;
