import { Bed, CheckCircle2, Sparkles, UserCheck } from "lucide-react";

import type { KpiItem } from "@/types/shared.types";

import type { Room } from "./room.types";

export const roomKpisData: KpiItem[] = [
  {
    id: 1,
    iconKey: Bed,
    title: "Total Rooms",
    value: "84",
    details: "All registered rooms",
  },
  {
    id: 2,
    iconKey: CheckCircle2,
    title: "Available",
    value: "32",
    details: "Ready for new bookings",
  },
  {
    id: 3,
    iconKey: UserCheck,
    title: "Occupied",
    value: "38",
    details: "Currently occupied",
  },
  {
    id: 4,
    iconKey: Sparkles,
    title: "Housekeeping",
    value: "14",
    details: "Cleaning or service required",
  },
];

export const roomsData: Room[] = [
  {
    id: "1",
    name: "Deluxe Garden View",
    roomNumber: "101",
    roomType: { name: "deluxe" },
    floor: 1,
    description: "Spacious room with a garden view.",
    occupancyStatus: "VACANT",
    housekeepingStatus: "CLEAN",
    isActive: true,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-09-20"),
  },
  {
    id: "2",
    name: "Premium Suite",
    roomNumber: "102",
    roomType: { name: "suite" },
    floor: 1,
    description: "Luxury suite with a king-size bed.",
    occupancyStatus: "OCCUPIED",
    housekeepingStatus: "CLEAN",
    isActive: true,
    createdAt: new Date("2026-01-16"),
    updatedAt: new Date("2026-09-22"),
  },
  {
    id: "3",
    name: "Executive Room",
    roomNumber: "201",
    roomType: { name: "executive" },
    floor: 2,
    description: "Ideal for business travelers.",
    occupancyStatus: "RESERVED",
    housekeepingStatus: "CLEAN",
    isActive: true,
    createdAt: new Date("2026-02-01"),
    updatedAt: new Date("2026-09-21"),
  },
  {
    id: "4",
    name: "Standard Twin",
    roomNumber: "202",
    roomType: { name: "standard" },
    floor: 2,
    description: "Twin-bed room for two guests.",
    occupancyStatus: "VACANT",
    housekeepingStatus: "DIRTY",
    isActive: true,
    createdAt: new Date("2026-02-05"),
    updatedAt: new Date("2026-09-23"),
  },
  {
    id: "5",
    name: "Family Room",
    roomNumber: "203",
    roomType: { name: "family" },
    floor: 2,
    description: "Perfect for families with children.",
    occupancyStatus: "OCCUPIED",
    housekeepingStatus: "CLEAN",
    isActive: true,
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-09-22"),
  },
  {
    id: "6",
    name: "Superior King",
    roomNumber: "301",
    roomType: { name: "superior" },
    floor: 3,
    description: "King-size bed with city view.",
    occupancyStatus: "VACANT",
    housekeepingStatus: "CLEANING",
    isActive: true,
    createdAt: new Date("2026-04-01"),
    updatedAt: new Date("2026-09-23"),
  },
  {
    id: "7",
    name: "Honeymoon Suite",
    roomNumber: "302",
    roomType: { name: "suite" },
    floor: 3,
    description: "Romantic suite with a private balcony.",
    occupancyStatus: "RESERVED",
    housekeepingStatus: "CLEAN",
    isActive: true,
    createdAt: new Date("2026-04-15"),
    updatedAt: new Date("2026-09-21"),
  },
  {
    id: "8",
    name: "Maintenance Room",
    roomNumber: "303",
    roomType: { name: "standard" },
    floor: 3,
    description: "Temporarily unavailable due to maintenance.",
    occupancyStatus: "OUT_OF_ORDER",
    housekeepingStatus: "DIRTY",
    isActive: false,
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-09-18"),
  },
];
